In [ ]:
# Imports
import pandas as pd
import numpy as np
import os
from datetime import datetime

# Base directory for the original data (lambda function for dynamic date range)
base_dir   = lambda date: f"./data/export_{date}"

dates_list = ['3.12.16-4.11.16', '4.12.16-5.12.16']

original_activity1 = pd.read_csv(f'{base_dir(dates_list[0])}/dailyActivity.csv')
original_activity2 = pd.read_csv(f'{base_dir(dates_list[1])}/dailyActivity.csv')

In [33]:
# Limit data range from dataframe
def limit_date_range(df, date_range):
    sep_dates = date_range.split('-')
    initial_date = str(datetime.strptime(sep_dates[0], '%m.%d.%y').date())
    last_date    = str(datetime.strptime(sep_dates[1], '%m.%d.%y').date())

    range = df[(df['ActivityDay'] >= initial_date) & (df['ActivityDay'] <= last_date)]

    return range

# Merge dataframes
def connect_dailyActivity_files():
    df_dailyActivity = pd.read_csv(f'{base_dir(dates_list[0])}/dailyActivity.csv')
    df_dailyActivity = limit_date_range(df_dailyActivity, dates_list[0])
    for date in dates_list[1:]:
        df_con = pd.read_csv(f'{base_dir(date)}/dailyActivity.csv')
        df_con = limit_date_range(df_con, date)
        df_dailyActivity = pd.merge(
                df_dailyActivity, 
                df_con, 
                how='outer'
            )
    return df_dailyActivity

merged_dailyActivity = connect_dailyActivity_files()

merged_dailyActivity

,Id,ActivityDay,Calories,minutes_instances,SedentaryMinutes,LightActiveMinutes,ModeratelyActiveMinutes,VeryActiveMinutes,Steps,TotalMinutesAsleep,HalfDream,MinutesInBed,SleepsInstances
0,1503960366,2016-03-12,2228,1440,1056,216,60,108,19675,0.0,0.0,0.0,0.0
1,1503960366,2016-03-13,2101,1440,1106,197,32,105,17106,411.0,15.0,0.0,1.0
2,1503960366,2016-03-14,1829,1440,1142,228,28,42,10023,354.0,27.0,5.0,1.0
3,1503960366,2016-03-15,2112,1440,1037,260,87,56,15384,312.0,16.0,7.0,1.0
4,1503960366,2016-03-16,1965,1440,1122,198,55,65,13498,333.0,28.0,5.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1930,8877689391,2016-05-08,2844,1440,1169,139,93,39,10665,0.0,0.0,0.0,0.0
1931,8877689391,2016-05-09,3700,1440,1080,148,117,95,20156,0.0,0.0,0.0,0.0
1932,8877689391,2016-05-10,2830,1440,1179,136,85,40,10693,0.0,0.0,0.0,0.0
1933,8877689391,2016-05-11,3828,1440,1083,137,114,106,21391,0.0,0.0,0.0,0.0
1934,8877689391,2016-05-12,1658,840,693,60,52,35,7120,0.0,0.0,0.0,0.0

In [ ]:
# Dias con mas x calorias
# Días con más de 10.000 pasos
# Días completos
# Días registrados
# Días sin datos
# Días sedentaros
# Días con sueño registrado

In [29]:
merged_dailyActivity = connect_dailyActivity_files()

print("1 - ",len(original_activity1))
print("2 - ",len(original_activity2))
print("3 - ",len(merged_dailyActivity))


merged_dailyActivity['ActivityDay'] = pd.to_datetime(merged_dailyActivity['ActivityDay'])

first_day       = merged_dailyActivity['ActivityDay'].min()
last_day        = merged_dailyActivity['ActivityDay'].max()
diff_days_range = last_day - first_day

print()

print(first_day)
print(last_day)

print()

print(f'Cantidad de días    : {diff_days_range.days}')
print(f'Cantidad de horas   : {diff_days_range.days * 24}')
print(f'Cantidad de minutos : {diff_days_range.days * 1440}')

4.12.16-5.12.16
1 -  1021
2 -  934
3 -  1935

2016-03-12 00:00:00
2016-05-12 00:00:00

Cantidad de días    : 61
Cantidad de horas   : 1464
Cantidad de minutos : 87840

In [ ]:
################################################
################################################
################################################

In [12]:
sep_dates = dates_list[0].split('-')
print(sep_dates)
t1 = str(datetime.strptime(sep_dates[0], '%m.%d.%y').date())
t2 = str(datetime.strptime(sep_dates[1], '%m.%d.%y').date())

# merged_dailyActivity = connect_dailyActivity_files()
merged_dailyActivity = pd.read_csv(f'{base_dir(dates_list[0])}/dailyActivity.csv')
range = merged_dailyActivity[(merged_dailyActivity['ActivityDay'] >= t1) & (merged_dailyActivity['ActivityDay'] <= t2) ]

range.groupby(['Id',]).agg(
    fecha_inicial=('ActivityDay', 'min'),         # Find the earliest available date
    fecha_final=('ActivityDay', 'max'),           # Find the latest available date
    cantidad_registros=('ActivityDay', 'count'),  # Count the number of records
    suma_registros=('Calories', 'sum')               # Sum of the main column
)

range

['3.12.16', '4.11.16']

,Id,ActivityDay,Calories,minutes_instances,SedentaryMinutes,LightActiveMinutes,ModeratelyActiveMinutes,VeryActiveMinutes,Steps,TotalMinutesAsleep,HalfDream,MinutesInBed,SleepsInstances
0,1503960366,2016-03-12,2228,1440,1056,216,60,108,19675,0.0,0.0,0.0,0.0
1,1503960366,2016-03-13,2101,1440,1106,197,32,105,17106,411.0,15.0,0.0,1.0
2,1503960366,2016-03-14,1829,1440,1142,228,28,42,10023,354.0,27.0,5.0,1.0
3,1503960366,2016-03-15,2112,1440,1037,260,87,56,15384,312.0,16.0,7.0,1.0
4,1503960366,2016-03-16,1965,1440,1122,198,55,65,13498,333.0,28.0,5.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,8877689391,2016-04-07,2943,1440,1179,128,85,48,10876,0.0,0.0,0.0,0.0
1016,8877689391,2016-04-08,4192,1440,926,204,207,103,22989,0.0,0.0,0.0,0.0
1017,8877689391,2016-04-09,3839,1440,1030,153,153,104,16451,0.0,0.0,0.0,0.0
1018,8877689391,2016-04-10,4514,1440,1013,134,162,131,28481,0.0,0.0,0.0,0.0
1019,8877689391,2016-04-11,2814,1440,1185,119,92,44,10557,0.0,0.0,0.0,0.0

In [3]:
merged_dailyActivity = connect_dailyActivity_files()

print("1 - ",len(original_activity1))
print("2 - ",len(original_activity2))
print("3 - ",len(merged_dailyActivity))


merged_dailyActivity['ActivityDay'] = pd.to_datetime(merged_dailyActivity['ActivityDay'])

first_day       = merged_dailyActivity['ActivityDay'].min()
last_day        = merged_dailyActivity['ActivityDay'].max()
diff_days_range = last_day - first_day

print()

print(first_day)
print(last_day)

print()

print(f'Cantidad de días    : {diff_days_range.days}')
print(f'Cantidad de horas   : {diff_days_range.days * 24}')
print(f'Cantidad de minutos : {diff_days_range.days * 1440}')

NameError: name 'pd' is not defined

In [50]:
merged_dailyActivity[merged_dailyActivity['Id'] == 1624580081].to_csv(f"./test.csv", index=False)

In [55]:
merged_dailyActivity.groupby(['Id','ActivityDay']).agg(
    fecha_inicial=('ActivityDay', 'count'),         # Find the earliest available date
    cantidad_dias=('ActivityDay', 'nunique'),  # Count the number of records
)

                        fecha_inicial  cantidad_dias
Id         ActivityDay
1503960366 2016-03-12               1              1
           2016-03-13               1              1
           2016-03-14               1              1
           2016-03-15               1              1
           2016-03-16               1              1
...                               ...            ...
8877689391 2016-05-08               1              1
           2016-05-09               1              1
           2016-05-10               1              1
           2016-05-11               1              1
           2016-05-12               1              1

[1935 rows x 2 columns]

In [57]:
merged_dailyActivity.groupby(['Id',]).agg(
    fecha_inicial=('ActivityDay', 'min'),         # Find the earliest available date
    fecha_final=('ActivityDay', 'max'),           # Find the latest available date
    cantidad_dias=('ActivityDay', 'count'),  # Count the number of records
    dias_unicos=('ActivityDay', 'nunique'),  # Count the number of records
    suma_calorias=('Calories', 'sum')               # Sum of the main column
)

,fecha_inicial,fecha_final,cantidad_dias,dias_unicos,suma_calorias
Id,,,,,
1503960366,2016-03-12,2016-05-11,61,61,116640
1624580081,2016-03-12,2016-05-12,63,62,90201
1644430081,2016-03-12,2016-05-11,60,60,172994
1844505072,2016-03-12,2016-05-12,63,62,95927
1927972279,2016-03-12,2016-05-12,63,62,149921
2022484408,2016-03-12,2016-05-12,63,62,159869
2026352035,2016-03-12,2016-05-12,63,62,94138
2320127002,2016-03-12,2016-05-12,63,62,99768
2347167796,2016-03-12,2016-04-29,50,49,103715
2873212765,2016-03-12,2016-05-12,62,62,118253
2891001357,2016-04-05,2016-04-05,1,1,1121
3372868164,2016-03-12,2016-05-01,50,50,95630
3977333714,2016-03-12,2016-05-10,61,60,85979
4020332650,2016-03-12,2016-05-12,63,62,157802
4057192912,2016-03-12,2016-04-15,36,35,68520
4319703577,2016-03-12,2016-05-12,59,59,121855
4388161847,2016-04-12,2016-05-12,31,31,94191
4445114986,2016-03-12,2016-05-12,63,62,137704
4558609924,2016-03-12,2016-05-12,63,62,119406
4702921684,2016-03-12,2016-05-12,62,62,183588
5553957443,2016-03-12,2016-05-12,63,62,114703
5577150313,2016-03-12,2016-05-11,61,61,207293
6117666160,2016-03-12,2016-05-09,57,57,126508
6290855005,2016-03-12,2016-05-09,50,50,133626
6391747486,2016-03-12,2016-04-09,29,29,52245
6775888955,2016-03-12,2016-05-07,55,55,131603
6962181067,2016-03-12,2016-05-12,63,62,130943
7007744171,2016-03-12,2016-05-07,58,57,149560
7086361926,2016-03-12,2016-05-12,63,62,152683
8053475328,2016-03-12,2016-05-12,63,62,185447
8253242879,2016-03-12,2016-04-29,49,49,80252
8378563200,2016-03-12,2016-05-12,63,62,212995
8583815059,2016-03-12,2016-05-11,58,58,143592
8792009665,2016-03-12,2016-05-09,60,59,117880
8877689391,2016-03-12,2016-05-12,63,62,215614

In [116]:
original_activity1.groupby(['Id',]).agg(
    fecha_inicial=('ActivityDay', 'min'),         # Find the earliest available date
    fecha_final=('ActivityDay', 'max'),           # Find the latest available date
    cantidad_registros=('ActivityDay', 'count'),  # Count the number of records
    suma_registros=('Calories', 'sum')               # Sum of the main column
)

           fecha_inicial fecha_final  cantidad_registros  suma_registros
Id
1503960366    2016-03-12  2016-04-11                  31           60345
1624580081    2016-03-12  2016-04-12                  32           44251
1644430081    2016-03-12  2016-04-10                  30           88776
1844505072    2016-03-12  2016-04-12                  32           47182
1927972279    2016-03-12  2016-04-12                  32           82596
2022484408    2016-03-12  2016-04-12                  32           82279
2026352035    2016-03-12  2016-04-12                  32           46436
2320127002    2016-03-12  2016-04-12                  32           46363
2347167796    2016-03-12  2016-04-12                  32           66984
2873212765    2016-03-12  2016-04-11                  31           59140
2891001357    2016-04-05  2016-04-05                   1            1121
3372868164    2016-03-12  2016-04-10                  30           57030
3977333714    2016-03-12  2016-04-12                  32           40637
4020332650    2016-03-12  2016-04-12                  32           84111
4057192912    2016-03-12  2016-04-12                  32           60670
4319703577    2016-03-12  2016-04-08                  28           60024
4445114986    2016-03-12  2016-04-12                  32           70161
4558609924    2016-03-12  2016-04-12                  32           56425
4702921684    2016-03-12  2016-04-11                  31           91682
5553957443    2016-03-12  2016-04-12                  32           56575
5577150313    2016-03-12  2016-04-11                  31          106484
6117666160    2016-03-12  2016-04-09                  29           65883
6290855005    2016-03-12  2016-04-02                  22           58305
6391747486    2016-03-12  2016-04-09                  29           52245
6775888955    2016-03-12  2016-04-09                  29           76193
6962181067    2016-03-12  2016-04-12                  32           69483
7007744171    2016-03-12  2016-04-12                  32           83458
7086361926    2016-03-12  2016-04-12                  32           73354
8053475328    2016-03-12  2016-04-12                  32           94144
8253242879    2016-03-12  2016-04-11                  31           46343
8378563200    2016-03-12  2016-04-12                  32          106826
8583815059    2016-03-12  2016-04-08                  28           64134
8792009665    2016-03-12  2016-04-12                  32           61013
8877689391    2016-03-12  2016-04-12                  32          109927